export const types = Object.freeze({
  TOGGLE_PLAY_AUDIO_TRACK: 'TOGGLE_PLAY_AUDIO_TRACK',
  STOP_PLAY_AUDIO_TRACK: 'STOP_PLAY_AUDIO_TRACK',
  START_PLAY_AUDIO_TRACK: 'START_PLAY_AUDIO_TRACK',
  SET_TRACKS_DATA: 'SET_TRACKS_DATA',
  SET_IS_TRACKS_DATA_LOADING: 'SET_IS_TRACKS_DATA_LOADING',
});
